import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const products: Product[] = [
  {
    id: '1',
    name: 'Apollo Intensa Emozione',
    price: 2710000,
    description: 'A masterpiece of raw power and aerodynamic design. With a V12 engine, it promises an intense, emotional driving experience.',
    category: 'Hypercar',
    imageUrl: PlaceHolderImages[8].imageUrl,
    imageHint: PlaceHolderImages[8].imageHint,
  },
  {
    id: '2',
    name: 'Jaguar E-Type',
    price: 350000,
    description: 'An icon of automotive history. The E-Type combines breathtaking beauty with high performance, a true classic.',
    category: 'Classic',
    imageUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
  },
  {
    id: '3',
    name: 'Rivian R1T',
    price: 73000,
    description: 'The future of adventure. This all-electric truck offers unparalleled off-road capability and cutting-edge technology.',
    category: 'Electric',
    imageUrl: PlaceHolderImages[10].imageUrl,
    imageHint: PlaceHolderImages[10].imageHint,
  },
  {
    id: '4',
    name: 'Rolls-Royce Phantom',
    price: 460000,
    description: 'The pinnacle of automotive luxury. The Phantom provides a serene and supremely comfortable ride, crafted with exquisite materials.',
    category: 'Luxury',
    imageUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
  },
  {
    id: '5',
    name: 'Honda e',
    price: 35000,
    description: 'A charming and agile electric car designed for the city. Its retro-futuristic looks and minimalist interior make it unique.',
    category: 'Electric',
    imageUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
  },
  {
    id: '6',
    name: 'Tesla Cybertruck',
    price: 81900,
    description: 'Built for any planet. With its stainless-steel exoskeleton and armored glass, the Cybertruck is unlike anything else on the road.',
    category: 'Electric',
    imageUrl: PlaceHolderImages[5].imageUrl,
    imageHint: PlaceHolderImages[5].imageHint,
  },
  {
    id: '7',
    name: 'Ford Mustang Shelby GT500',
    price: 79420,
    description: 'Pure American muscle. The Shelby GT500 is the most powerful street-legal Ford ever built, with a supercharged V8.',
    category: 'Muscle',
    imageUrl: PlaceHolderImages[6].imageUrl,
    imageHint: PlaceHolderImages[6].imageHint,
  },
  {
    id: '8',
    name: 'Chrysler Pacifica Hybrid',
    price: 53425,
    description: 'The ultimate family vehicle. This plug-in hybrid minivan offers space, comfort, and efficiency without compromise.',
    category: 'Family',
    imageUrl: PlaceHolderImages[7].imageUrl,
    imageHint: PlaceHolderImages[7].imageHint,
  },
  {
    id: '9',
    name: 'Porsche 911 Carrera',
    price: 114400,
    description: 'The quintessential sports car. Timeless design, rear-engine layout, and a perfect balance of performance and daily usability.',
    category: 'Sports Car',
    imageUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
  },
  {
    id: '10',
    name: 'Mazda MX-5 Miata',
    price: 28985,
    description: 'The definition of a fun-to-drive roadster. Lightweight, agile, and connected to the road, it delivers pure driving joy.',
    category: 'Convertible',
    imageUrl: PlaceHolderImages[9].imageUrl,
    imageHint: PlaceHolderImages[9].imageHint,
  },
  {
    id: '11',
    name: 'Mercedes-Benz G-Class',
    price: 139900,
    description: 'An off-road legend turned luxury icon. The G-Class boasts military-grade toughness with a lavish, high-tech interior.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
  },
  {
    id: '12',
    name: 'BMW M4 Competition',
    price: 85100,
    description: 'A high-performance coupe that blends aggressive styling with razor-sharp handling and a potent twin-turbo inline-six engine.',
    category: 'Coupe',
    imageUrl: PlaceHolderImages[11].imageUrl,
    imageHint: PlaceHolderImages[11].imageHint,
  },
];
