import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const products: Product[] = [
  {
    id: '1',
    brand: 'Apollo',
    model: 'Intensa Emozione',
    version: 'Launch Edition',
    price: 2710000,
    description: 'Una obra maestra de potencia bruta y diseño aerodinámico. Con un motor V12, promete una experiencia de conducción intensa y emocional.',
    category: 'Hypercar',
    imageUrl: PlaceHolderImages[8].imageUrl,
    imageHint: PlaceHolderImages[8].imageHint,
  },
  {
    id: '2',
    brand: 'Jaguar',
    model: 'E-Type',
    version: 'Series 1',
    price: 350000,
    description: 'Un ícono de la historia del automóvil. El E-Type combina una belleza impresionante con un alto rendimiento, un verdadero clásico.',
    category: 'Classic',
    imageUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
  },
  {
    id: '3',
    brand: 'Rivian',
    model: 'R1T',
    version: 'Adventure',
    price: 73000,
    description: 'El futuro de la aventura. Esta camioneta totalmente eléctrica ofrece una capacidad todoterreno inigualable y tecnología de vanguardia.',
    category: 'Electric',
    imageUrl: PlaceHolderImages[10].imageUrl,
    imageHint: PlaceHolderImages[10].imageHint,
  },
  {
    id: '4',
    brand: 'Rolls-Royce',
    model: 'Phantom',
    version: 'Extended Wheelbase',
    price: 460000,
    description: 'La cúspide del lujo automotriz. El Phantom ofrece un viaje sereno y sumamente cómodo, elaborado con materiales exquisitos.',
    category: 'Luxury',
    imageUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
  },
  {
    id: '5',
    brand: 'Honda',
    model: 'e',
    version: 'Advance',
    price: 35000,
    description: 'Un coche eléctrico encantador y ágil diseñado para la ciudad. Su aspecto retro-futurista y su interior minimalista lo hacen único.',
    category: 'Electric',
    imageUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
  },
  {
    id: '6',
    brand: 'Tesla',
    model: 'Cybertruck',
    version: 'Cyberbeast',
    price: 81900,
    description: 'Construido para cualquier planeta. Con su exoesqueleto de acero inoxidable y vidrio blindado, el Cybertruck no se parece a nada en la carretera.',
    category: 'Electric',
    imageUrl: PlaceHolderImages[5].imageUrl,
    imageHint: PlaceHolderImages[5].imageHint,
  },
  {
    id: '7',
    brand: 'Ford',
    model: 'Mustang Shelby',
    version: 'GT500',
    price: 79420,
    description: 'Puro músculo americano. El Shelby GT500 es el Ford de calle más potente jamás construido, con un V8 sobrealimentado.',
    category: 'Muscle',
    imageUrl: PlaceHolderImages[6].imageUrl,
    imageHint: PlaceHolderImages[6].imageHint,
  },
  {
    id: '8',
    brand: 'Chrysler',
    model: 'Pacifica',
    version: 'Hybrid Pinnacle',
    price: 53425,
    description: 'El vehículo familiar definitivo. Este monovolumen híbrido enchufable ofrece espacio, comodidad y eficiencia sin concesiones.',
    category: 'Family',
    imageUrl: PlaceHolderImages[7].imageUrl,
    imageHint: PlaceHolderImages[7].imageHint,
  },
  {
    id: '9',
    brand: 'Porsche',
    model: '911 Carrera',
    version: 'S',
    price: 114400,
    description: 'El coche deportivo por excelencia. Diseño atemporal, motor trasero y un equilibrio perfecto entre rendimiento y usabilidad diaria.',
    category: 'Sports Car',
    imageUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
  },
  {
    id: '10',
    brand: 'Mazda',
    model: 'MX-5 Miata',
    version: 'Grand Touring',
    price: 28985,
    description: 'La definición de un roadster divertido de conducir. Ligero, ágil y conectado a la carretera, ofrece pura alegría al volante.',
    category: 'Convertible',
    imageUrl: PlaceHolderImages[9].imageUrl,
    imageHint: PlaceHolderImages[9].imageHint,
  },
  {
    id: '11',
    brand: 'Mercedes-Benz',
    model: 'G-Class',
    version: 'G 63 AMG',
    price: 139900,
    description: 'Una leyenda todoterreno convertida en icono de lujo. El Clase G cuenta con una robustez de grado militar con un interior lujoso y de alta tecnología.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
  },
  {
    id: '12',
    brand: 'BMW',
    model: 'M4',
    version: 'Competition',
    price: 85100,
    description: 'Un coupé de alto rendimiento que combina un estilo agresivo con un manejo preciso y un potente motor de seis cilindros en línea biturbo.',
    category: 'Coupe',
    imageUrl: PlaceHolderImages[11].imageUrl,
    imageHint: PlaceHolderImages[11].imageHint,
  },
];
