import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const products: Product[] = [
  {
    id: '1',
    brand: 'Toyota',
    model: 'Corolla',
    version: 'XEi 2.0',
    price: 24500,
    description: 'Sedán confiable, económico y muy durable.',
    category: 'Sedan',
    imageUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
  },
  {
    id: '2',
    brand: 'Honda',
    model: 'Civic',
    version: 'EXL',
    price: 27500,
    description: 'Modelo moderno con excelente rendimiento y confort.',
    category: 'Sedan',
    imageUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
  },
  {
    id: '3',
    brand: 'Ford',
    model: 'Focus',
    version: 'SE 2.0',
    price: 21000,
    description: 'Auto ágil con muy buena respuesta en ciudad y ruta.',
    category: 'Hatchback',
    imageUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
  },
  {
    id: '4',
    brand: 'Chevrolet',
    model: 'Cruze',
    version: 'LTZ',
    price: 23000,
    description: 'Buen equilibrio entre comodidad y equipamiento.',
    category: 'Sedan',
    imageUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
  },
  {
    id: '5',
    brand: 'Volkswagen',
    model: 'Golf',
    version: 'Highline',
    price: 26000,
    description: 'Hatchback premium con excelente calidad de manejo.',
    category: 'Hatchback',
    imageUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
  },
  {
    id: '6',
    brand: 'Volkswagen',
    model: 'T-Cross',
    version: 'Comfortline',
    price: 28500,
    description: 'SUV compacto muy cómodo y seguro para la familia.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[5].imageUrl,
    imageHint: PlaceHolderImages[5].imageHint,
  },
  {
    id: '7',
    brand: 'Nissan',
    model: 'Kicks',
    version: 'Advance',
    price: 27000,
    description: 'SUV liviana, económica y con gran equipamiento.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[6].imageUrl,
    imageHint: PlaceHolderImages[6].imageHint,
  },
  {
    id: '8',
    brand: 'Renault',
    model: 'Kwid',
    version: 'Intense',
    price: 12500,
    description: 'Pequeño, económico y práctico para la ciudad.',
    category: 'Citycar',
    imageUrl: PlaceHolderImages[7].imageUrl,
    imageHint: PlaceHolderImages[7].imageHint,
  },
  {
    id: '9',
    brand: 'Peugeot',
    model: '208',
    version: 'Allure',
    price: 19000,
    description: 'Diseño atractivo con muy buen confort interior.',
    category: 'Hatchback',
    imageUrl: PlaceHolderImages[8].imageUrl,
    imageHint: PlaceHolderImages[8].imageHint,
  },
  {
    id: '10',
    brand: 'Peugeot',
    model: '3008',
    version: 'GT Line',
    price: 39000,
    description: 'SUV moderno con diseño premium y excelente tecnología.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[9].imageUrl,
    imageHint: PlaceHolderImages[9].imageHint,
  },
  {
    id: '11',
    brand: 'Fiat',
    model: 'Cronos',
    version: 'Precision',
    price: 18500,
    description: 'Sedán versátil con bajo consumo y buen espacio.',
    category: 'Sedan',
    imageUrl: PlaceHolderImages[10].imageUrl,
    imageHint: PlaceHolderImages[10].imageHint,
  },
  {
    id: '12',
    brand: 'Fiat',
    model: 'Pulse',
    version: 'Impetus',
    price: 24000,
    description: 'SUV compacto con diseño moderno y gran equipamiento.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[11].imageUrl,
    imageHint: PlaceHolderImages[11].imageHint,
  },
  {
    id: '13',
    brand: 'Hyundai',
    model: 'Creta',
    version: 'Premium',
    price: 30000,
    description: 'SUV confiable con excelente habitabilidad y confort.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
  },
  {
    id: '14',
    brand: 'Hyundai',
    model: 'i20',
    version: 'Sport',
    price: 17500,
    description: 'Compacto eficiente, ideal para uso urbano diario.',
    category: 'Hatchback',
    imageUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
  },
  {
    id: '15',
    brand: 'Kia',
    model: 'Seltos',
    version: 'EX',
    price: 32000,
    description: 'SUV equilibrado con buen nivel de confort y tecnología.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
  },
  {
    id: '16',
    brand: 'Kia',
    model: 'Rio',
    version: 'LX',
    price: 18500,
    description: 'Hatchback confiable con excelente eficiencia de consumo.',
    category: 'Hatchback',
    imageUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
  },
  {
    id: '17',
    brand: 'BMW',
    model: '118i',
    version: 'Sport Line',
    price: 42000,
    description: 'Auto premium con gran desempeño y terminaciones.',
    category: 'Hatchback',
    imageUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
  },
  {
    id: '18',
    brand: 'BMW',
    model: 'X1',
    version: 'sDrive',
    price: 52000,
    description: 'SUV premium con alto confort y avanzada tecnología.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[5].imageUrl,
    imageHint: PlaceHolderImages[5].imageHint,
  },
  {
    id: '19',
    brand: 'Audi',
    model: 'A3',
    version: 'Sportback',
    price: 45000,
    description: 'Auto premium con excelente desempeño y calidad.',
    category: 'Hatchback',
    imageUrl: PlaceHolderImages[6].imageUrl,
    imageHint: PlaceHolderImages[6].imageHint,
  },
  {
    id: '20',
    brand: 'Audi',
    model: 'Q3',
    version: 'S Line',
    price: 55000,
    description: 'SUV elegante con gran tecnología y seguridad.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[7].imageUrl,
    imageHint: PlaceHolderImages[7].imageHint,
  },
  {
    id: '21',
    brand: 'Mercedes-Benz',
    model: 'Clase A',
    version: 'A200',
    price: 48000,
    description: 'Compacto premium con excelente confort y diseño.',
    category: 'Hatchback',
    imageUrl: PlaceHolderImages[8].imageUrl,
    imageHint: PlaceHolderImages[8].imageHint,
  },
  {
    id: '22',
    brand: 'Mercedes-Benz',
    model: 'GLA',
    version: '200 Progressive',
    price: 62000,
    description: 'SUV lujosa con conducción suave y tecnología avanzada.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[9].imageUrl,
    imageHint: PlaceHolderImages[9].imageHint,
  },
  {
    id: '23',
    brand: 'Jeep',
    model: 'Renegade',
    version: 'Longitude',
    price: 31000,
    description: 'SUV robusto con espíritu aventurero y buena tecnología.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[10].imageUrl,
    imageHint: PlaceHolderImages[10].imageHint,
  },
  {
    id: '24',
    brand: 'Jeep',
    model: 'Compass',
    version: 'Limited',
    price: 42000,
    description: 'SUV mediana con excelente equipamiento y confort.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[11].imageUrl,
    imageHint: PlaceHolderImages[11].imageHint,
  },
  {
    id: '25',
    brand: 'Citroën',
    model: 'C4 Cactus',
    version: 'Feel Pack',
    price: 20000,
    description: 'SUV liviana, cómoda y con muy buen equipamiento.',
    category: 'SUV',
    imageUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
  }
];
